server:
  port: 8083

spring:
  application:
    name: booking-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
  datasource:
    url: jdbc:postgresql://localhost:5434/db_travel_booking
    username: postgres
    password: postgrespassword
