import {
  DestinationVm,
  TourDetailVm,
  UserVm,
  BookingDetailVm,
  PaymentVm,
  TripRecommendationVm,
} from "./types";

export const MOCK_USERS: UserVm[] = [
  {
    userId: "11111111-1111-1111-1111-111111111111",
    email: "tourist@example.com",
    fullName: "Nguyễn Văn Tourist",
    status: "ACTIVE",
    roles: ["ROLE_TOURIST"],
    phoneNumber: "0901234567",
    createdAt: "2026-08-01T10:00:00Z",
  },
  {
    userId: "22222222-2222-2222-2222-222222222222",
    email: "guide@example.com",
    fullName: "Trần Văn Hướng Dẫn",
    status: "ACTIVE",
    roles: ["ROLE_GUIDE"],
    phoneNumber: "0912345678",
    createdAt: "2026-08-02T10:00:00Z",
  },
  {
    userId: "33333333-3333-3333-3333-333333333333",
    email: "admin@example.com",
    fullName: "Quản Trị Viên Hệ Thống",
    status: "ACTIVE",
    roles: ["ROLE_ADMIN"],
    phoneNumber: "0988888888",
    createdAt: "2026-08-01T08:00:00Z",
  },
  {
    userId: "user-guide-pending-01",
    email: "pendingguide@example.com",
    fullName: "Phạm Thị Chờ Duyệt",
    status: "PENDING_APPROVAL",
    roles: ["ROLE_GUIDE"],
    phoneNumber: "0933333333",
    createdAt: "2026-08-20T14:30:00Z",
  },
];

export const MOCK_DESTINATIONS: DestinationVm[] = [
  {
    id: "dest-dn",
    name: "Đà Nẵng & Hội An",
    city: "Đà Nẵng",
    country: "Việt Nam",
    imageUrl: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=800&q=80",
    tourCount: 12,
  },
  {
    id: "dest-pq",
    name: "Đảo Ngọc Phú Quốc",
    city: "Phú Quốc",
    country: "Việt Nam",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
    tourCount: 8,
  },
  {
    id: "dest-hg",
    name: "Hà Giang Loop - Cao Nguyên Đá",
    city: "Hà Giang",
    country: "Việt Nam",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80",
    tourCount: 6,
  },
  {
    id: "dest-nt",
    name: "Vịnh Biển Nha Trang",
    city: "Nha Trang",
    country: "Việt Nam",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    tourCount: 9,
  },
  {
    id: "dest-hl",
    name: "Vịnh Hạ Long",
    city: "Quảng Ninh",
    country: "Việt Nam",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80",
    tourCount: 15,
  },
  {
    id: "dest-sp",
    name: "Sapa Mờ Sương",
    city: "Lào Cai",
    country: "Việt Nam",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    tourCount: 10,
  },
];

export const MOCK_TOURS: TourDetailVm[] = [
  {
    tourId: "tour-01",
    code: "TOUR-DN-3N2D",
    title: "Tour Khám Phá Đà Nẵng - Ba Na Hills - Phố Cổ Hội An 3N2Đ",
    description: "Hành trình trải nghiệm tuyệt vời miền Trung: Chinh phục đỉnh Bà Nà Hills, check-in Cầu Vàng huyền thoại, ngắm hoàng hôn Phố cổ Hội An rực rỡ đèn lồng và thưởng thức ẩm thực đặc sản cao cấp.",
    status: "PUBLISHED",
    createdAt: "2026-08-01T10:00:00Z",
    updatedAt: "2026-08-10T15:00:00Z",
    duration: "3 Ngày 2 Đêm",
    imageUrl: "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=800&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 128,
    includedServices: [
      "Vé cáp treo khứ hồi Bà Nà Hills",
      "Khách sạn 4 sao trung tâm biển Mỹ Khê",
      "Các bữa ăn theo chương trình ẩm thực địa phương",
      "Xe du lịch đời mới đưa đón suốt hành trình",
      "Hướng dẫn viên chuyên nghiệp theo đoàn",
    ],
    excludedServices: [
      "Vé máy bay khứ hồi (Hỗ trợ đặt hộ)",
      "Chi phí cá nhân ngoài chương trình",
      "Tiền tip cho HDV và tài xế",
    ],
    destinations: [MOCK_DESTINATIONS[0]],
    itineraries: [
      {
        id: "itin-01-1",
        dayNumber: 1,
        title: "Đón Sân Bay - Check-in Biển Mỹ Khê - Ngắm Cầu Rồng Phun Lửa",
        content: "Xe và HDV đón quý khách tại Sân bay Đà Nẵng. Nhận phòng khách sạn nghỉ ngơi, tự do tắm biển Mỹ Khê. Buổi tối thưởng thức đặc sản Bánh tráng thịt heo 2 đầu da, dạo phố sông Hàn.",
      },
      {
        id: "itin-01-2",
        dayNumber: 2,
        title: "KDL Bà Nà Hills - Cầu Vàng - Khám Phá Phố Cổ Hội An",
        content: "Khởi hành đi Bà Nà Hills, di chuyển tuyến cáp treo đạt 4 kỷ lục thế giới. Check-in Cầu Vàng, Làng Pháp, Fantasy Park. Chiều di chuyển tham quan Phố cổ Hội An, thả đèn hoa đăng sông Hoài.",
      },
      {
        id: "itin-01-3",
        dayNumber: 3,
        title: "Danh Thắng Ngũ Hành Sơn - Mua Sắm Chợ Hàn - Tiễn Đoàn",
        content: "Tham quan Ngũ Hành Sơn, Chùa Linh Ứng Bán Đảo Sơn Trà. Mua sắm đặc sản chả bò, hải sản khô tại Chợ Hàn. Xe tiễn quý khách ra sân bay Đà Nẵng.",
      },
    ],
    schedules: [
      {
        id: "sch-01-1",
        departureTime: "2026-09-01T07:30:00Z",
        arrivalTime: "2026-09-03T18:00:00Z",
        priceAdult: 4500000,
        priceChild: 3150000,
        totalSeats: 25,
        availableSeats: 12,
        assignedGuideId: "user-guide-01",
        assignedGuideName: "Trần Văn Hướng Dẫn",
      },
      {
        id: "sch-01-2",
        departureTime: "2026-09-15T07:30:00Z",
        arrivalTime: "2026-09-17T18:00:00Z",
        priceAdult: 4750000,
        priceChild: 3320000,
        totalSeats: 30,
        availableSeats: 20,
        assignedGuideId: "user-guide-01",
        assignedGuideName: "Trần Văn Hướng Dẫn",
      },
    ],
  },
  {
    tourId: "tour-02",
    code: "TOUR-PQ-4N3D",
    title: "Tour Thiên Đường Nắng Vàng Phú Quốc 4N3Đ - VinWonders & Safari",
    description: "Khám phá đảo ngọc Phú Quốc với tour trọn gói: Trải nghiệm cáp treo Hòn Thơm vượt biển dài nhất thế giới, lặn ngắm san hô 4 đảo, vui chơi không giới hạn VinWonders & Vinpearl Safari.",
    status: "PUBLISHED",
    createdAt: "2026-08-03T11:00:00Z",
    updatedAt: "2026-08-12T09:00:00Z",
    duration: "4 Ngày 3 Đêm",
    imageUrl: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
    galleryUrls: [
      "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 96,
    includedServices: [
      "Vé VinWonders & Safari Phú Quốc",
      "Tour cano 4 đảo & Lặn ngắm san hô",
      "Resort 4 sao sát biển có hồ bơi vô cực",
      "Các bữa ăn hải sản tươi sống",
    ],
    excludedServices: ["Vé máy bay khứ hồi", "Chi phí cá nhân"],
    destinations: [MOCK_DESTINATIONS[1]],
    itineraries: [
      {
        id: "itin-02-1",
        dayNumber: 1,
        title: "Đón Sân Bay Phú Quốc - Check-in Sunset Sanato - Dinh Cậu",
        content: "Nghỉ dưỡng tại resort 4 sao, ngắm hoàng hôn Sunset Sanato nổi tiếng.",
      },
      {
        id: "itin-02-2",
        dayNumber: 2,
        title: "Khu Vui Chơi Giải Trí VinWonders & Công Viên Bán Hoang Dã Safari",
        content: "Khám phá thế giới động vật bán hoang dã và thủy cung Thủy Cung Cung Điện Hải Vương.",
      },
      {
        id: "itin-02-3",
        dayNumber: 3,
        title: "Tour Cano 4 Đảo Nam Đảo - Lặn San Ho Hòn Mây Rút",
        content: "Cano đưa quý khách vượt sóng ngắm san hô tự nhiên, tự do bơi lội bãi Sao.",
      },
      {
        id: "itin-02-4",
        dayNumber: 4,
        title: "Mua Sắm Đặc Sản Ngọc Trai, Nước Mắm - Tiễn Sân Bay",
        content: "Tham quan cơ sở sản xuất nước mắm truyền thống Khải Hoàn, mua đặc sản.",
      },
    ],
    schedules: [
      {
        id: "sch-02-1",
        departureTime: "2026-09-05T08:00:00Z",
        arrivalTime: "2026-09-08T17:00:00Z",
        priceAdult: 6200000,
        priceChild: 4340000,
        totalSeats: 20,
        availableSeats: 8,
        assignedGuideId: "user-guide-01",
        assignedGuideName: "Trần Văn Hướng Dẫn",
      },
    ],
  },
  {
    tourId: "tour-03",
    code: "TOUR-HG-3N2D",
    title: "Tour Phượt Hà Giang Loop - Mã Pí Lèng - Chinh Phục Cột Cờ Lũng Cú",
    description: "Trải nghiệm cung đường đèo Mã Pí Lèng huyền thoại, đi thuyền trên dòng sông Nho Quế xanh ngọc bích, giao lưu văn hóa H'Mông tại Bản Lô Lô Chải.",
    status: "PUBLISHED",
    createdAt: "2026-08-05T14:00:00Z",
    updatedAt: "2026-08-14T10:00:00Z",
    duration: "3 Ngày 2 Đêm",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80",
    rating: 5.0,
    reviewCount: 64,
    includedServices: [
      "Xe giường nằm VIP Hà Nội - Hà Giang",
      "Xe máy gầm cao + Xế bản địa lái kèm",
      "Homestay bản địa ấm cúng & Lẩu gà đen",
      "Thuyền ngắm Hẻm Tu Sản sông Nho Quế",
    ],
    excludedServices: ["Chi phí tiêu dùng cá nhân"],
    destinations: [MOCK_DESTINATIONS[2]],
    itineraries: [
      {
        id: "itin-03-1",
        dayNumber: 1,
        title: "Hà Nội - Thành Phố Hà Giang - Quản Bạ - Yên Minh",
        content: "Vượt dốc Bắc Sum, ngắm Cổng Trời Quản Bạ và Núi Đôi Cô Tiên.",
      },
      {
        id: "itin-03-2",
        dayNumber: 2,
        title: "Đèo Mã Pí Lèng - Sông Nho Quế - Cột Cờ Lũng Cú - Đồng Văn",
        content: "Check-in điểm cực Bắc Cột Cờ Lũng Cú, săn mây đèo Mã Pí Lèng.",
      },
      {
        id: "itin-03-3",
        dayNumber: 3,
        title: "Chợ Phiên Đồng Văn - Dinh Thự Vua Mèo - Về Hà Nội",
        content: "Trải nghiệm không khí chợ phiên vùng cao rực rỡ sắc màu.",
      },
    ],
    schedules: [
      {
        id: "sch-03-1",
        departureTime: "2026-09-10T20:00:00Z",
        arrivalTime: "2026-09-13T22:00:00Z",
        priceAdult: 3850000,
        priceChild: 2695000,
        totalSeats: 16,
        availableSeats: 5,
        assignedGuideId: "user-guide-01",
        assignedGuideName: "Trần Văn Hướng Dẫn",
      },
    ],
  },
  {
    tourId: "tour-04",
    code: "TOUR-NT-3N2D",
    title: "Tour Khám Phá Biển Đảo Nha Trang - VinWonders & Đảo Điệp Sơn",
    description: "Đến với thành phố biển Nha Trang sôi động, check-in con đường đi bộ giữa biển độc đáo tại đảo Điệp Sơn, vui chơi VinWonders và thư giãn tắm bùn khoáng nóng.",
    status: "PUBLISHED",
    createdAt: "2026-08-08T09:00:00Z",
    updatedAt: "2026-08-16T12:00:00Z",
    duration: "3 Ngày 2 Đêm",
    imageUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 82,
    includedServices: ["Cano cao tốc", "Khách sạn 4 sao", "Vé VinWonders", "Bữa ăn hải sản"],
    excludedServices: ["Vé máy bay"],
    destinations: [MOCK_DESTINATIONS[3]],
    itineraries: [
      { id: "itin-04-1", dayNumber: 1, title: "Đón Đoàn - Tháp Bà Ponagar - Tắm Bùn I-Resort", content: "Tham quan văn hóa Chăm Pa và thư giãn suối khoáng." },
      { id: "itin-04-2", dayNumber: 2, title: "Tour 3 Đảo Vịnh Nha Trang - Lặn Biển Hòn Mun", content: "Lặn biển bằng bình khí hoặc ngắm san hô qua tàu đáy kính." },
      { id: "itin-04-3", dayNumber: 3, title: "Vui Chơi VinWonders Hòn Tre - Tiễn Đoàn", content: "Thưởng thức Tata Show hoành tráng trước khi ra sân bay Cam Ranh." },
    ],
    schedules: [
      {
        id: "sch-04-1",
        departureTime: "2026-09-20T07:00:00Z",
        arrivalTime: "2026-09-22T19:00:00Z",
        priceAdult: 4200000,
        priceChild: 2940000,
        totalSeats: 30,
        availableSeats: 18,
      },
    ],
  },
  {
    tourId: "tour-05",
    code: "TOUR-HL-2N1D",
    title: "Tour Du Thuyền 5 Sao Vịnh Hạ Long - Đảo Titop & Hang Sửng Sốt",
    description: "Nghỉ dưỡng đẳng cấp trên du thuyền 5 sao lướt sóng qua hàng nghìn hòn đảo đá vôi kỳ vĩ. Chèo thuyền Kayak, chèo SUP, tập Tai Chi buổi sáng và ăn tối buffet hải sản.",
    status: "PUBLISHED",
    createdAt: "2026-08-09T08:00:00Z",
    updatedAt: "2026-08-15T11:00:00Z",
    duration: "2 Ngày 1 Đêm",
    imageUrl: "https://images.unsplash.com/photo-1528127269322-539801943592?auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 110,
    includedServices: ["Phòng Suite sang trọng trên Du Thuyền", "Tất cả 4 bữa ăn cao cấp", "Vé chèo Kayak", "Vé danh thắng Vịnh Hạ Long"],
    excludedServices: ["Xe đưa đón Hà Nội - Hạ Long (Hỗ trợ 300k/người)"],
    destinations: [MOCK_DESTINATIONS[4]],
    itineraries: [
      { id: "itin-05-1", dayNumber: 1, title: "Check-in Du Thuyền 5 Star - Hang Sửng Sốt - Sunset Party", content: "Thưởng thức tiệc trà chiều ngắm hoàng hôn buông xuống vịnh." },
      { id: "itin-05-2", dayNumber: 2, title: "Tập Taichi - Chèo Kayak Đảo Titop - Cảng Tuần Châu", content: "Tắm biển bãi Titop và chinh phục đỉnh núi ngắm toàn cảnh vịnh." },
    ],
    schedules: [
      {
        id: "sch-05-1",
        departureTime: "2026-09-08T11:30:00Z",
        arrivalTime: "2026-09-09T12:00:00Z",
        priceAdult: 3500000,
        priceChild: 2450000,
        totalSeats: 20,
        availableSeats: 10,
      },
    ],
  },
  {
    tourId: "tour-06",
    code: "TOUR-SP-3N2D",
    title: "Tour Sa Pa Săn Mây Fansipan - Bản Cát Cát - Moana Sapa",
    description: "Săn mây trên 'Nóc nhà Đông Dương' Fansipan ở độ cao 3.143m, dạo bước qua nấc thang bản Cát Cát của người H'Mông và check-in sống ảo tại Moana Sapa.",
    status: "PUBLISHED",
    createdAt: "2026-08-10T10:00:00Z",
    updatedAt: "2026-08-18T16:00:00Z",
    duration: "3 Ngày 2 Đêm",
    imageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 75,
    includedServices: ["Cáp treo Fansipan", "Khách sạn 4 sao view núi", "Xe giường nằm VIP", "Lẩu cá hồi Sa Pa"],
    excludedServices: ["Chi phí mua sắm quà lưu niệm"],
    destinations: [MOCK_DESTINATIONS[5]],
    itineraries: [
      { id: "itin-06-1", dayNumber: 1, title: "Hà Nội - Sa Pa - Tham Quan Bản Cát Cát", content: "Trải nghiệm chụp ảnh trang phục dân tộc tại thung lũng Mường Hoa." },
      { id: "itin-06-2", dayNumber: 2, title: "Chinh Phục Đỉnh Fansipan 3.143m - Moana Check-in", content: "Đi cáp treo ngắm thung lũng mây bồng bềnh." },
      { id: "itin-06-3", dayNumber: 3, title: "Nhà Thờ Đá Sa Pa - Mua Sắm Chợ Sa Pa - Về Hà Nội", content: "Thưởng thức đồ nướng Sa Pa đặc sắc." },
    ],
    schedules: [
      {
        id: "sch-06-1",
        departureTime: "2026-09-12T06:30:00Z",
        arrivalTime: "2026-09-14T19:00:00Z",
        priceAdult: 3290000,
        priceChild: 2300000,
        totalSeats: 25,
        availableSeats: 15,
      },
    ],
  },
];

export const MOCK_BOOKINGS: BookingDetailVm[] = [
  {
    bookingId: "bk-mock-01",
    bookingCode: "BK20260820-X9A",
    userId: "11111111-1111-1111-1111-111111111111",
    userEmail: "tourist@example.com",
    userFullName: "Nguyễn Văn Tourist",
    tourScheduleId: "sch-01-1",
    tourId: "tour-01",
    tourTitle: "Tour Khám Phá Đà Nẵng - Ba Na Hills - Phố Cổ Hội An 3N2Đ",
    tourCode: "TOUR-DN-3N2D",
    departureTime: "2026-09-01T07:30:00Z",
    arrivalTime: "2026-09-03T18:00:00Z",
    totalAmount: 7650000,
    status: "CONFIRMED",
    passengers: [
      {
        id: "p-1",
        fullName: "Nguyễn Văn Tourist",
        passengerType: "ADULT",
        idCardNumber: "040099123456",
        price: 4500000,
        checkedIn: true,
      },
      {
        id: "p-2",
        fullName: "Nguyễn Thùy Linh",
        passengerType: "CHILD",
        idCardNumber: "",
        price: 3150000,
        checkedIn: false,
      },
    ],
    createdAt: "2026-08-20T10:00:00Z",
    updatedAt: "2026-08-20T10:15:00Z",
  },
];

export const MOCK_PAYMENTS: PaymentVm[] = [
  {
    id: "pay-mock-01",
    bookingId: "bk-mock-01",
    amount: 7650000,
    paymentMethod: "VNPAY",
    status: "SUCCESS",
    transactionRef: "VNP20260820-8819",
    createdAt: "2026-08-20T10:10:00Z",
    updatedAt: "2026-08-20T10:12:00Z",
  },
];

export const SAMPLE_AI_RECOMMENDATION: TripRecommendationVm = {
  introduction:
    "Chào bạn! Dựa trên nhu cầu du lịch nghỉ dưỡng 3 Ngày 2 Đêm cùng gia đình tại Đà Nẵng, AI tư vấn của chúng tôi đề xuất Tour Khám phá Đà Nẵng - Bà Nà Hills - Phố cổ Hội An với lịch trình tối ưu và chi phí hợp lý.",
  recommendedTours: [
    {
      tourId: "tour-01",
      code: "TOUR-DN-3N2D",
      title: "Tour Khám Phá Đà Nẵng - Ba Na Hills - Phố Cổ Hội An 3N2Đ",
      pricePerAdult: 4500000,
      bookingUrl: "/tours/tour-01",
      reason: "Tour thiết kế cân bằng giữa nghỉ dưỡng biển Mỹ Khê và trải nghiệm vui chơi Bà Nà Hills cho cả người lớn và trẻ nhỏ.",
    },
  ],
  detailedItinerary: [
    {
      day: 1,
      title: "Đón Sân Bay - Biển Mỹ Khê - Ngắm Cầu Rồng Phun Lửa",
      description: "Thưởng thức Bánh tráng thịt heo 2 đầu da, dạo phố đêm Sông Hàn và ngắm Cầu Rồng.",
    },
    {
      day: 2,
      title: "KDL Bà Nà Hills - Check-in Cầu Vàng - Phố Cổ Hội An",
      description: "Đi cáp treo Bà Nà Hills, tham quan Cầu Vàng, buổi chiều dạo Phố cổ Hội An ngắm đèn lồng và thả hoa đăng.",
    },
    {
      day: 3,
      title: "Danh Thắng Ngũ Hành Sơn - Mua Sắm Chợ Hàn - Tiễn Đoàn",
      description: "Tham quan Ngũ Hành Sơn, mua đặc sản chả bò Đà Nẵng tại Chợ Hàn trước khi ra sân bay.",
    },
  ],
  cached: false,
};
